require "abdallah.options"
require "abdallah.plugins"
require "abdallah.nvim-tree"
require "abdallah.startup-script"
require "abdallah.cmp"
require "abdallah.colorscheme"
require "abdallah.lsp"
require "abdallah.telescope"
